# Generated by Django 5.1.6 on 2025-03-05 16:28

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_message_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(default='profiles/user-default.png', max_length=255, verbose_name='image'),
        ),
    ]
