trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  # Step 1: Pull the Docker image
  - script: |
      docker pull nexusameer/dev-search:latest
    displayName: 'Pull Docker Image from Docker Hub'

  # Step 2: Run the Docker container
  - script: |
      docker run --name django-container -p 8000:8000 --rm -d nexusameer/dev-search:latest
    displayName: 'Run Docker Container'

  # Step 3: Install prerequisites inside the container
  - script: |
      docker exec django-container python -m pip install --upgrade pip
      docker exec django-container pip install -r requirements.txt
    displayName: 'Install prerequisites inside container'

  # Step 4: Migrations, Static Files, and Tests
  - script: |
      docker exec django-container python manage.py migrate
      docker exec django-container python manage.py collectstatic --noinput
      docker exec django-container python manage.py test
    displayName: 'Run migrations, collect static files, and tests'

  # Step 5: Publish Test Results
  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/TEST-*.xml'
      testRunTitle: 'Django Tests in Docker'
    condition: succeededOrFailed()
