trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  System.Debug: true

steps:
- script: |
    echo $(DOCKER_PASSWORD) | docker login -u $(DOCKER_USERNAME) --password-stdin
  displayName: 'Docker Hub Login'
  env:
    DOCKER_USERNAME: 'nexusameer'  # Replace with your Docker Hub username
    DOCKER_PASSWORD: 'abc123ameer'  # Replace with your Docker Hub password
